apiVersion: v1
kind: LimitRange
metadata:
  name: limite-range-containers
spec:
  limits:
  - max:
      cpu: "500m"
      memory: "512Mi"
    min:
      cpu: "50m"
      memory: "32Mi"
    # Caso não seja especificado o resources no deployment, os seguintes valores serão aplicados
    default:
      cpu: "300m"
      memory: "256Mi"
    defaultRequest:
      cpu: "150m"
      memory: "128Mi"
    type: Container
