apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv01
  labels:
    type: local
spec:
  storageClassName: storage-manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/volumes/mongodb"
