apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: meu-pod
  template:
    metadata:
      labels:
        app: meu-pod
    spec:
      containers:
      - name: meu-container
        image: kubedevio/nginx-color:green