apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meu-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-pod
  template:
    metadata:
      labels:
        app: meu-pod
    spec:
      containers:
      - name: meu-container
        image: kubedevio/nginx-color:blue