apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: saiwmon/pedelogo-catalogo:v1.0.0
##       Utilizado integrado com o AWS ECR
#        image: 968644489163.dkr.ecr.us-east-1.amazonaws.com/pedelogo-catalogo:v1.0.0
        lifecycle:
          # Realizado em paralelo na inicialização do Pod.
          # Caso ocorra alguma falha, o Pod não será iniciado e ficará com status CrashLoopBackOff.
          # É possível utilizaro "httpGet" ao invés de "exec".
          postStart:
            exec:
              command:
              - "curl"
              - "-X"
              - "POST"
              - "http://pruu.herokuapp.com/dump/lifecyclestart" # Este site precisa estar UP.
          preStop:
            exec:
              command:
              - "curl"
              - "-X"
              - "POST"
              - "http://pruu.herokuapp.com/dump/lifecyclestop"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443 # Fins didáticos. Não será usada.
          name: https
        imagePullPolicy: IfNotPresent
        livenessProbe: # Verifica statuscode 200 por (1 * 5) = 5s e após isso faz o restart do pod.
          httpGet:
            path: /health
            port: 80
          failureThreshold: 1
          periodSeconds: 5
        readinessProbe: # Verifica statuscode 200 por (1 * 5) = 5s e após isso remove o endpoint não permitindo que sejam enviadas requisições para o pod até que o statuscode seja 200. Mas a pag de verificação deve ser diferente do livenessProbe.
          httpGet:
            path: /read
            port: 80
          failureThreshold: 1
          periodSeconds: 5
        startupProbe: # Aguarda statuscode 200 por (3 * 10) = 30s e após isso o livenessprobe poderá fazer suas verificações.
          httpGet:
            path: /health
            port: 80
          failureThreshold: 3
          periodSeconds: 10
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m" # 10% de CPU
          limits:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: api-configmap
        env:
        - name: Mongo__User
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: mongodb-secret
        - name: Mongo__Password
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongodb-secret
##     Utilizado integrado com o AWS ECR
#      imagePullSecrets:
#      - name: ecr-registry
